/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 orange.gltf 
Author: blakebella (https://sketchfab.com/blakebella)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/nissan-gt-r-r35-gt-297241223a564c39b3a70cd2d586a154
Title: Nissan GT-R R35 GT
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/orange.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.087}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Nissan_GTRTNR0_2017BadgeA_Material} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Nissan_GTRTNR0_2017EngineA_Material} />
        <lineSegments geometry={nodes.Object_4.geometry} material={materials.Nissan_GTRTNR0_2017Base_Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Nissan_GTRTNR0_2017Carbon1_Material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Nissan_GTRTNR0_2017Grille1A_Material} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Nissan_GTRTNR0_2017Grille7A_Material} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Nissan_GTRTNR0_2017Grille8A_Material} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Nissan_GTRTNR0_2017Grille9A_Material} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Nissan_GTRTNR0_2017SeatBelt_Material} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Nissan_GTRTNR0_2017WindowInside_Material} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Nissan_GTRTNR0_2017Window_Material} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Nissan_GTRTNR0_2017LightA_Material} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Nissan_GTRTNR0_2017InteriorA_Material} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Nissan_GTRTNR0_2017LicensePlateTNRA_Material} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Nissan_GTRTNR0_2017InteriorTillingColourZoneA_Material} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Nissan_GTRTNR3_2017Grille1D_Material.001']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.intercooler_remap} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.coloured_glass} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.gril_exhaust} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.redlight} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Nissan_GTRTNR0_2017Coloured_Material} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Nissan_GTRTNR0_2017Coloured_Material} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Nissan_GTRTNR0_2017Coloured_Material} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Nissan_GTRTNR0_2017Coloured_Material} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Nissan_GTRTNR0_2017Coloured_Material} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Nissan_GTRTNR0_2017Coloured_Material} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Nissan_GTRTNR0_2017Base_Material} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Nissan_GTRTNR0_2017Base_Material} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Nissan_GTRTNR0_2017PaintTNR_Material} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Nissan_GTRTNR0_2017PaintTNR_Material} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Nissan_GTRTNR0_2017PaintTNR_Material} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.Nissan_GTRTNR0_2017PaintTNR_Material} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.Nissan_GTRTNR0_2017PaintTNR_Material} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Nissan_GTRTNR3_2017Carbon1_Material} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.plastic} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.plastic} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.plastic} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.plastic} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.plastic} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.plastic} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.plastic} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.intercooler_gray} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.rotor} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.spoiler} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.spoiler} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.spoiler} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.spoke} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.spoke} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.spoke} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.spoke} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.tread} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.sidewall} />
      </group>
    </group>
  )
}

useGLTF.preload('/orange.gltf')
